# Generated by Django 3.2.4 on 2021-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='result',
            new_name='result1',
        ),
        migrations.AddField(
            model_name='user',
            name='result2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='result3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='result4',
            field=models.IntegerField(default=0),
        ),
    ]
