# Generated by Django 3.2.5 on 2021-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
            ],
        ),
    ]
